name: AST
channels:
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libuuid
  - lxml
  - ncurses
  - openssl
  - pip
  - pre-commit
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - python=3.8
  - pip:
      - fasteners==0.18
      - matplotlib==3.6.3
      - numpy==1.23.5
      - pandas==2.0.2
      - pylint==2.17.5
      - GitPython==3.1.31
      - prettytable==3.8.0
      - seaborn==0.12.2
      - rich=13.7.1
      - black==23.3.0
      - psutil==5.9.5
      - termplotlib==0.3.9
      - timeout-decorator==0.5.0
      - loguru==0.7.2
