name: AST
channels:
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - libuuid
  - lxml
  - ncurses
  - openssl
  - pip
  - pre-commit
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - python=3.12
  - pip:
      - fasteners==0.19
      - matplotlib==3.8.4
      - numpy==1.26.4
      - pandas==2.2.2
      - pylint==3.1.0
      - GitPython==3.1.43
      - prettytable==3.10.0
      - seaborn==0.13.2
      - rich==13.7.1
      - black==24.4.2
      - psutil==5.9.8
      - termplotlib==0.3.9
      - loguru==0.7.2
