name: Reproducibility Check
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        maven: [ '3.9.2' ]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "GRAALVM_HOME=$GRAALVM_HOME" >> $GITHUB_ENV
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17.0.7
    - run: echo "JAVA17_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - run: java -version
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install Rust and Cargo
      run: rustup update stable && rustup default stable
    - run: cargo --version
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        auto-update-conda: true
        channels: conda-forge,defaults
        activate-environment: AST
        environment-file: environment.yml
    - name: Clean caches & workspace
      run: make clean
    - run: echo "LOGURU_COLORIZE=NO" >> $GITHUB_ENV
    - name: Build
      run: cd src/scripts/merge_tools/merging && ./gradlew shadowJar
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
    - name: make check-merges-reproducibility
      run: |
        head -n 151 results/combined/result_raw.csv > temp.csv && mv temp.csv results/combined/result_raw.csv
        make check-merges-reproducibility
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
