name: Check style
on: [push, pull_request]
jobs:
  style:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        auto-update-conda: true
        mamba-version: "*"
        channels: conda-forge,defaults
        activate-environment: AST
        environment-file: environment.yml
    - name: Install shellcheck and checkbashisms
      run: sudo apt update && sudo apt install shellcheck devscripts
    - name: Check style
      run: make check-style
    - name: Check script diffs
      run: pwd && cd src/scripts/merge_tools && pwd && ls && ./check-implementations.sh
