name: Check style
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: psf/black@stable
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install shellcheck and checkbashisms
      run: sudo apt install shellcheck devscripts
    - name: Check style
      run: make style
