name: Reproducibility Check
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        maven: [ '3.9.2' ]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17.0.7
    - run: echo "JAVA17_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - run: java -version
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        auto-update-conda: true
        mamba-version: "*"
        channels: conda-forge,defaults
        activate-environment: AST
        environment-file: environment.yml
    - name: Clean caches & workspace
      run: make clean
    - run: echo "LOGURU_COLORIZE=NO" >> $GITHUB_ENV
    - name: Build
      run: |
        git submodule update --init --recursive
        cd src/scripts/merge_tools/merging && ./gradlew -q shadowJar
    - name: make check-merges-reproducibility
      run: |
        python3 src/python/replay_merge.py --merges_csv results/combined/result.csv -delete_workdir --idx 38-192
        head -n 151 results/combined/result.csv > temp.csv && mv temp.csv results/combined/result.csv
        make check-merges-reproducibility
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
