name: Check style
on: [push, pull_request]
jobs:
  style:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: psf/black@stable
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge
        python-version: 3.8
        activate-environment: AST
        environment-file: environment.yml
    - name: Install shellcheck and checkbashisms
      run: sudo apt install shellcheck devscripts
    - name: Check style
      run: make style
