name: Check style
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make check-python-style
