name: Update Overleaf with Plots

on:
  push:
    branches:
      - main  # Set this to match the branch name you use
      - automatic_plot_upload

jobs:
  update-overleaf:
    runs-on: ubuntu-latest

    steps:
      - uses: GuillaumeFalourd/setup-rsync@v1.2
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git Config and Credentials
        run: |
          git config --global user.email "github-cicd-bot@example.com"
          git config --global user.name "GitHub CI/CD Bot"

      - name: Create directory for Overleaf Repository
        run: mkdir -p ../AST-Merging-Evaluation-Paper

      - name: Clone Overleaf Repository
        env:
          OVERLEAF_GIT_REPO: ${{ secrets.OVERLEAF_GIT_REPO }}
        run: |
          git clone ${OVERLEAF_GIT_REPO} ../AST-Merging-Evaluation-Paper

      - name: Run make command to copy plots
        run: make copy-paper

      # Commit and push the changes to Overleaf if needed
      - name: Commit and Push to Overleaf
        run: |
          cd ../AST-Merging-Evaluation-Paper
          git add .
          git diff --staged --exit-code || (git commit -m "Automated plot updates by GitHub CI/CD Bot" && git push origin master)
