name: Run Small test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - run: echo "JAVA8_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - run: java -version
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
    - run: echo "JAVA11_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - run: java -version
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - run: echo "JAVA17_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - run: java -version
    - uses: actions/checkout@v3
    - uses: fregante/setup-git-user@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: python --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install maven
      run: |
        sudo apt update
        sudo apt install maven==3.8.6
    - name: Clean caches & workspace
      run: make clean
    - name: Build Java programs
      run: ./gradlew build
    - name: Run small test
      run: |
        git config --global user.email "example@example.com"
        git config --global user.name "Example Example"
        make small-test
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    - name: Debug
      if: always()
      run: |
        cat cache/test_result/tntim96_JSCover_b387036e5d7bba871c330469f2143c242f12a0d5_explanation.txt
