name: Small test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        maven: [ '3.9.2' ]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - run: echo "JAVA8_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - run: java -version
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
    - run: echo "JAVA11_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - run: java -version
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - run: echo "JAVA17_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - run: java -version
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        auto-update-conda: true
        mamba-version: "*"
        channels: conda-forge,defaults
        activate-environment: AST
        environment-file: environment.yml
    - name: Install PdfLaTeX
      run: sudo apt update && sudo apt install texlive-latex-extra -y
    - name: Install maven
      uses: s4u/setup-maven-action@v1.12.0
      with:
        java-version: 17
        maven-version: ${{ matrix.maven }}
    - name: Clean caches & workspace
      run: make clean
    - run: echo "LOGURU_COLORIZE=NO" >> $GITHUB_ENV
    - name: Run small test
      run: |
        git config --global user.email "example@example.com"
        git config --global user.name "Example Example"
        git config --global merge.customMerge.name "Always incorrect custom merge driver"
        git config --global merge.customMerge.driver 'fake-merge-driver %O %A %B %L %P'
        make small-test
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
